image:
  file: .devcontainer/Dockerfile
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: false
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
vscode:
  extensions:
    - bungcip.better-toml
    - llvm-vs-code-extensions.vscode-clangd
    - vadimcn.vscode-lldb
    - matklad.rust-analyzer
    - revng.llvm-ir
tasks:
  - name: Run build and watch
    init: cargo build --tests
    command: cargo watch -x 'test'
