# https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        informational: true #Ignore failed coverage
    patch:
      default:
        informational: true #Ignore failed coverage

flags:
  unittests:
    paths:
      - compiler/
      - src/
      - libs/
    carryforward: true
  littests:
    paths:
      - compiler/
      - src/
      - libs/
    carryforward: true
