# https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        informational: true #Ignore failed coverage
    patch:
      default:
        informational: true #Ignore failed coverage
