[workspace]
release = false
release_always = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
publish = false
git_only = true
git_tag_name = "v{{ version }}"

[[package]]
name = "rusty"
release = true
version_group = "external"

[[package]]
name = "plc_driver"
release = true
version_group = "external"

[[package]]
name = "iec61131std"
release = true
version_group = "external"
