//! Model representation of `.cfc` files.
//!
//! This file has been generated by a LLM with the instruction to look at the official XSD file and the
//! existing fixtures in this crate.

use serde::Deserialize;

pub fn from_str(xml: &str) -> Result<Pou, quick_xml::DeError> {
    quick_xml::de::from_str(xml)
}

/// The polymorphic `<CommonObject>` and `<FbdObject>` elements pick their concrete type through an
/// `xsi:type` attribute, which serde's derived enum deserialization cannot dispatch on. This macro
/// implements a [`serde::de::Deserialize`] that reads the attribute and forwards the remaining map to
/// the matching variant.
macro_rules! impl_deserialize_for_xsi_type_enum {
    ($enum:ty, $tag:literal, $($cases:tt)*) => {
        impl<'de> serde::de::Deserialize<'de> for $enum {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
            where
                D: serde::de::Deserializer<'de>,
            {
                use serde::de::{Error, MapAccess, Visitor};

                struct TheVisitor;
                impl<'de> Visitor<'de> for TheVisitor {
                    type Value = $enum;

                    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                        f.write_str("expecting map with tag in ")?;
                        f.write_str($tag)
                    }

                    fn visit_map<A>(self, mut map: A) -> Result<Self::Value, A::Error>
                    where
                        A: MapAccess<'de>,
                    {
                        let tag: String = loop {
                            match map.next_entry::<String, String>()? {
                                Some((attribute, value)) if attribute == $tag => {
                                    break value.rsplit(':').next().unwrap_or(&value).to_string();
                                }
                                Some((attribute, _)) if attribute.starts_with("@xmlns") => continue,
                                Some((attribute, _)) => {
                                    return Err(A::Error::unknown_field(&attribute, &[$tag]))
                                }
                                None => return Err(A::Error::missing_field($tag)),
                            }
                        };

                        let de = serde::de::value::MapAccessDeserializer::new(map);
                        quick_xml::deserialize_match!(tag, de, $enum, $($cases)*)
                    }
                }
                deserializer.deserialize_map(TheVisitor)
            }
        }
    }
}

/// A `<...Variables>` pin list comes wrapped in an extra element (e.g. `<InputVariables><InputVariable/>
/// </InputVariables>`), which serde cannot flatten into a `Vec` on its own. This macro defines a
/// `deserialize_with` function stripping that wrapper so [`Block`] can hold plain vectors.
macro_rules! variable_list_deserializer {
    ($name:ident, $tag:literal, $type:ty) => {
        fn $name<'de, D>(deserializer: D) -> Result<Vec<$type>, D::Error>
        where
            D: serde::de::Deserializer<'de>,
        {
            #[derive(Deserialize)]
            struct Wrapper {
                #[serde(rename = $tag, default)]
                variables: Vec<$type>,
            }

            Ok(Wrapper::deserialize(deserializer)?.variables)
        }
    };
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub enum Pou {
    Program(PouBody),
    FunctionBlock(PouBody),
    Function(PouBody),
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct PouBody {
    #[serde(rename = "@name")]
    pub name: String,
    #[serde(rename = "AddData", default, deserialize_with = "pou_declaration")]
    pub declaration: String,
    #[serde(rename = "MainBody", deserialize_with = "main_body_network")]
    pub network: Network,
}

#[derive(Debug, Clone, PartialEq, Default, Deserialize)]
pub struct Network {
    #[serde(rename = "CommonObject", default)]
    pub common_objects: Vec<CommonObject>,
    #[serde(rename = "FbdObject", default)]
    pub objects: Vec<FbdObject>,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Operation {
    Call(Block),
    Sink(DataSink),
    Return(Return),
}

#[derive(Debug, Clone, PartialEq)]
pub enum CommonObject {
    Comment(Comment),
    Connector(Connector),
    Continuation(Continuation),
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Comment {}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Connector {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@label")]
    pub label: String,
    #[serde(rename = "ConnectionPointIn", default, deserialize_with = "connection_point_in")]
    pub connection_in: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Continuation {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@label")]
    pub label: String,
    #[serde(rename = "ConnectionPointOut", deserialize_with = "connection_point_out")]
    pub connection_out: u64,
}

#[derive(Debug, Clone, PartialEq)]
pub enum FbdObject {
    Block(Block),
    DataSource(DataSource),
    DataSink(DataSink),
    Unconnected(Unconnected),
    Jump(Jump),
    Return(Return),
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Block {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@typeName")]
    pub type_name: String,
    #[serde(rename = "@instanceName")]
    pub instance_name: Option<String>,
    #[serde(rename = "AddData", deserialize_with = "block_add_data")]
    pub add_data: AddData,
    #[serde(rename = "InputVariables", default, deserialize_with = "input_variables")]
    pub inputs: Vec<InputVariable>,
    #[serde(rename = "InOutVariables", default, deserialize_with = "inout_variables")]
    pub inouts: Vec<InputVariable>,
    #[serde(rename = "OutputVariables", default, deserialize_with = "output_variables")]
    pub outputs: Vec<OutputVariable>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct InputVariable {
    #[serde(rename = "@parameterName")]
    pub parameter_name: String,
    #[serde(rename = "@negated", default)]
    pub negated: bool,
    #[serde(rename = "ConnectionPointIn", default, deserialize_with = "connection_point_in")]
    pub connection_in: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct OutputVariable {
    #[serde(rename = "@parameterName")]
    pub parameter_name: String,
    #[serde(rename = "ConnectionPointOut", deserialize_with = "connection_point_out")]
    pub connection_out: u64,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct DataSource {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@identifier")]
    pub identifier: String,
    #[serde(rename = "ConnectionPointOut", deserialize_with = "connection_point_out")]
    pub connection_out: u64,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct DataSink {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@identifier")]
    pub identifier: String,
    #[serde(rename = "AddData", default)]
    pub add_data: AddData,
    #[serde(rename = "ConnectionPointIn", default, deserialize_with = "connection_point_in")]
    pub connection_in: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Unconnected {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@complexIdentifier")]
    pub complex_identifier: String,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Jump {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "@targetNetworkLabel")]
    pub target_network_label: String,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Return {
    #[serde(rename = "@globalId")]
    pub global_id: u64,
    #[serde(rename = "AddData", default)]
    pub add_data: AddData,
    #[serde(rename = "ConnectionPointIn", default, deserialize_with = "connection_point_in")]
    pub connection_in: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Default, Deserialize)]
#[serde(from = "RawAddData")]
pub struct AddData {
    pub priority: Option<u64>,
    pub negated: bool,
}

#[derive(Deserialize)]
struct RawAddData {
    #[serde(rename = "Data", default)]
    data: Vec<RawData>,
}

#[derive(Deserialize)]
struct RawData {
    #[serde(rename = "textDeclaration")]
    text_declaration: Option<RawTextDeclaration>,
    #[serde(rename = "EvaluationPriority")]
    evaluation_priority: Option<RawEvaluationPriority>,
    negated: Option<RawNegated>,
}

#[derive(Deserialize)]
struct RawTextDeclaration {
    content: RawContent,
}

#[derive(Deserialize)]
struct RawContent {
    #[serde(rename = "$text", default)]
    text: String,
}

#[derive(Deserialize)]
struct RawEvaluationPriority {
    #[serde(rename = "@priorityInNetwork")]
    priority: Option<u64>,
}

#[derive(Deserialize)]
struct RawNegated {
    #[serde(rename = "@value")]
    value: bool,
}

impl_deserialize_for_xsi_type_enum! {
    CommonObject, "@type",
    ("Comment" => Comment(Comment)),
    ("Connector" => Connector(Connector)),
    ("Continuation" => Continuation(Continuation)),
}

impl_deserialize_for_xsi_type_enum! {
    FbdObject, "@type",
    ("Block" => Block(Block)),
    ("DataSource" => DataSource(DataSource)),
    ("DataSink" => DataSink(DataSink)),
    ("Unconnected" => Unconnected(Unconnected)),
    ("Jump" => Jump(Jump)),
    ("Return" => Return(Return)),
}

impl From<RawAddData> for AddData {
    fn from(raw: RawAddData) -> AddData {
        AddData {
            priority: raw.data.iter().find_map(|data| data.evaluation_priority.as_ref()?.priority),
            negated: raw
                .data
                .iter()
                .find_map(|data| data.negated.as_ref())
                .is_some_and(|negated| negated.value),
        }
    }
}

fn pou_declaration<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    let raw = RawAddData::deserialize(deserializer)?;
    let declaration = raw.data.into_iter().find_map(|data| data.text_declaration);

    Ok(declaration.map(|declaration| declaration.content.text).unwrap_or_default())
}

fn main_body_network<'de, D>(deserializer: D) -> Result<Network, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct RawMainBody {
        #[serde(rename = "BodyContent")]
        content: RawBodyContent,
    }

    #[derive(Deserialize)]
    struct RawBodyContent {
        #[serde(rename = "@type")]
        kind: String,
        #[serde(rename = "Network", default)]
        network: Network,
    }

    let body = RawMainBody::deserialize(deserializer)?;
    match body.content.kind.rsplit(':').next() {
        Some("FBD") => Ok(body.content.network),
        _ => Err(serde::de::Error::custom(format!("unsupported body type `{}`", body.content.kind))),
    }
}

/// Unlike sinks and returns, whose [`AddData`] tolerates a missing priority, a block must carry one:
/// its results are materialized into temporaries at its place in the evaluation order, so a block
/// without a priority has no defined place to be evaluated at.
fn block_add_data<'de, D>(deserializer: D) -> Result<AddData, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    let add_data = AddData::deserialize(deserializer)?;
    if add_data.priority.is_none() {
        return Err(serde::de::Error::custom("block is missing an `EvaluationPriority` entry"));
    }

    Ok(add_data)
}

fn connection_point_in<'de, D>(deserializer: D) -> Result<Option<u64>, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct RawConnectionPointIn {
        #[serde(rename = "Connection")]
        connection: Option<RawConnection>,
    }

    #[derive(Deserialize)]
    struct RawConnection {
        #[serde(rename = "@refConnectionPointOutId")]
        id: u64,
    }

    let point = RawConnectionPointIn::deserialize(deserializer)?;
    Ok(point.connection.map(|connection| connection.id))
}

fn connection_point_out<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct RawConnectionPointOut {
        #[serde(rename = "@connectionPointOutId")]
        id: u64,
    }

    Ok(RawConnectionPointOut::deserialize(deserializer)?.id)
}

variable_list_deserializer!(input_variables, "InputVariable", InputVariable);
variable_list_deserializer!(inout_variables, "InOutVariable", InputVariable);
variable_list_deserializer!(output_variables, "OutputVariable", OutputVariable);

impl Pou {
    fn body(&self) -> &PouBody {
        match self {
            Pou::Program(body) | Pou::FunctionBlock(body) | Pou::Function(body) => body,
        }
    }

    #[allow(dead_code)]
    pub fn name(&self) -> &str {
        &self.body().name
    }

    pub fn declaration(&self) -> &str {
        &self.body().declaration
    }

    pub fn network(&self) -> &Network {
        &self.body().network
    }
}

impl Network {
    pub fn get_ordered_operations(&self) -> Vec<Operation> {
        let mut operations = Vec::new();
        for object in &self.objects {
            match object {
                FbdObject::Block(block) => operations.push(Operation::Call(block.clone())),
                FbdObject::DataSink(sink) => operations.push(Operation::Sink(sink.clone())),
                FbdObject::Return(ret) => operations.push(Operation::Return(ret.clone())),
                _ => (),
            }
        }

        operations.sort_by_key(Operation::get_priority);
        operations
    }
}

impl Operation {
    pub fn get_name(&self) -> &str {
        match self {
            Operation::Call(value) => &value.type_name,
            Operation::Sink(value) => &value.identifier,
            Operation::Return(_) => "conditional return",
        }
    }

    pub fn get_priority(&self) -> Option<u64> {
        match self {
            Operation::Call(block) => block.add_data.priority,
            Operation::Sink(sink) => sink.add_data.priority,
            Operation::Return(ret) => ret.add_data.priority,
        }
    }

    /// Returns the IDs of all values this operation consumes, i.e. every incoming connection. A call
    /// consumes one value per connected input and inout pin, a sink or return at most one.
    pub fn get_connections_in(&self) -> Vec<u64> {
        match self {
            Operation::Call(block) => {
                block.inputs.iter().chain(&block.inouts).filter_map(|pin| pin.connection_in).collect()
            }
            Operation::Sink(sink) => sink.connection_in.into_iter().collect(),
            Operation::Return(ret) => ret.connection_in.into_iter().collect(),
        }
    }

    pub fn get_global_id(&self) -> u64 {
        match self {
            Operation::Call(block) => block.global_id,
            Operation::Sink(sink) => sink.global_id,
            Operation::Return(ret) => ret.global_id,
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::model::Block;

    #[test]
    fn block_priority() {
        let xml = r#"
            <FbdObject xsi:type="Block" globalId="3" typeName="myAdd">
                <AddData>
                    <Data name="www.iec.ch/61131-10/EvaluationPriority" handleUnknown="discard">
                        <EvaluationPriority priorityInNetwork="2"/>
                    </Data>
                </AddData>
            </FbdObject>
        "#;
        let block: Block = quick_xml::de::from_str(xml).unwrap();
        assert_eq!(block.add_data.priority, Some(2));

        // A block carries its priority in `AddData`, so a block without one is rejected outright.
        let xml = r#"<FbdObject xsi:type="Block" globalId="3" typeName="myAdd"/>"#;
        let result: Result<Block, _> = quick_xml::de::from_str(xml);
        assert!(result.is_err());
    }

    #[test]
    fn deserializes_ide_export() {
        let xml = include_str!("../fixtures/valid/function_call/mainProgram.cfc");
        let pou = crate::model::from_str(xml).unwrap();

        assert_eq!(pou.name(), "mainProgram");
        assert_eq!(pou.network().objects.len(), 4);
    }

    #[test]
    fn deserializes_untouched_ide_default() {
        let xml = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <ppx:Program xmlns:ppx="www.iec.ch/public/TC65SC65BWG7TF10" xmlns:rxt="www.iec.ch/public/TC65SC65BWG7TF10/Recommendation" name="program_0">
                <ppx:AddData>
                    <ppx:Data name="http://www.bachmann.at/xml/PLC" handleUnknown="implementation">
                        <textDeclaration>
                            <content>PROGRAM program_0
VAR

END_VAR
</content>
                        </textDeclaration>
                    </ppx:Data>
                </ppx:AddData>
                <ppx:MainBody>
                    <ppx:BodyContent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ppx:FBD">
                        <ppx:Network/>
                    </ppx:BodyContent>
                </ppx:MainBody>
            </ppx:Program>"#;
        let pou = crate::model::from_str(xml).unwrap();

        assert_eq!(pou.name(), "program_0");
        assert!(pou.declaration().starts_with("PROGRAM program_0"));
        assert!(pou.network().objects.is_empty());
    }
}
