[alias]
tw1 = "test --workspace -- --test-threads=1"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    "-C",
    "link-arg=--target=aarch64-linux-gnu",
]
linker = "clang"

[target.aarch64-apple-darwin]
rustflags = [
    "-C",
    "link-arg=-lxar"
]

[profile.profiling]
inherits = "release"
debug = true
