(********************
*
* Converts DT to DATE
*
*********************)
{external}
FUNCTION DATE_AND_TIME_TO_DATE : DATE
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to LDATE
*
*********************)
{external}
FUNCTION LDATE_AND_TIME_TO_LDATE : LDATE
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts DT to TOD
*
*********************)
{external}
FUNCTION DATE_AND_TIME_TO_TIME_OF_DAY : TOD
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to LTOD
*
*********************)
{external}
FUNCTION LDATE_AND_TIME_TO_LTIME_OF_DAY : LTOD
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts LTIME to TIME
*
*********************)
{external}
FUNCTION LTIME_TO_TIME : TIME
VAR_INPUT
    in : LTIME;
END_VAR
END_FUNCTION

(********************
*
* Converts TIME to LTIME
*
*********************)
{external}
FUNCTION TIME_TO_LTIME : LTIME
VAR_INPUT
    in : TIME;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to DT
*
*********************)
{external}
FUNCTION LDT_TO_DT : DT
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to DATE
*
*********************)
{external}
FUNCTION LDT_TO_DATE : DATE
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to LTOD
*
*********************)
{external}
FUNCTION LDT_TO_LTOD : LTOD
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts LDT to TOD
*
*********************)
{external}
FUNCTION LDT_TO_TOD : TOD
VAR_INPUT
    in : LDT;
END_VAR
END_FUNCTION

(********************
*
* Converts DT to LDT
*
*********************)
{external}
FUNCTION DT_TO_LDT : LDT
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts DT to DATE
*
*********************)
{external}
FUNCTION DT_TO_DATE : DATE
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts DT to LTOD
*
*********************)
{external}
FUNCTION DT_TO_LTOD : LTOD
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts DT to TOD
*
*********************)
{external}
FUNCTION DT_TO_TOD : TOD
VAR_INPUT
    in : DT;
END_VAR
END_FUNCTION

(********************
*
* Converts LTOD to TOD
*
*********************)
{external}
FUNCTION LTOD_TO_TOD : TOD
VAR_INPUT
    in : LTOD;
END_VAR
END_FUNCTION

(********************
*
* Converts TOD to LTOD
*
*********************)
{external}
FUNCTION TOD_TO_LTOD : LTOD
VAR_INPUT
    in : TOD;
END_VAR
END_FUNCTION
