// C implementation of the {external} function block body.
// The ctor (including array init) is generated by the ST compiler
// with --constructors-only; this file only provides the FB body.

typedef struct {
    void* __vtable;
    int arr[5];
    int x;
} myFb_t;

// The body function matches the ST function block name
void myFb(myFb_t* self) {
    // no-op: the array and x are initialized by the compiler-generated ctor
    (void)self;
}
