#!/bin/sh
# Minimal 'not' utility: inverts the exit code of a command.
# Provided as a fallback for LIT environments where LLVM's 'not' is not installed.
# See: https://llvm.org/docs/CommandGuide/not.html
"$@"
if [ $? -eq 0 ]; then
    exit 1
else
    exit 0
fi
