[book]
authors = ["Ghaith Hachem", "Mathias Rieder", "Alexander Ulmer"]
language = "en"
multilingual = false
src = "src"
title = "RuSTy User Documentation"
[output.html]
additional-js = ["iecst.min.js", "llvm.min.js", "custom.js", "highlight.js"]

[output.html.fold]
enable = true
level = 0

[preprocessor.errors]
command = "../target/release/errorcode_book_generator"
err_location = "../compiler/plc_diagnostics/src/diagnostics/error_codes"
err_target = "using_rusty/error_configuration.md"
