[book]
authors = ["Ghaith Hachem", "Mathias Rieder", "Alexander Ulmer"]
language = "en"
multilingual = false
src = "src"
title = "RuSTy User Documentation"
[output.html]
additional-js = ["iecst.min.js", "llvm.min.js", "custom.js", "highlight.js"]
