name: Metrics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: rust-llvm
  IMAGE_VERSION: latest

jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    container: ghcr.io/plc-lang/rust-llvm:latest

    steps:
    - uses: actions/checkout@v3

    - name: Update git permissions
      run: |
        git config --global --add safe.directory /__w/rusty/rusty

    - name: Collect metrics (Git)
      shell: bash
      if: github.ref_name == 'master'
      run: |
        cargo metrics --reporter=git

    - name: Collect metrics (Local)
      shell: bash
      if: github.ref_name != 'master'
      run: |
        cargo metrics
