name: Metrics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: rust-llvm
  IMAGE_VERSION: latest

jobs:
  metrics:
    name: Metrics
    runs-on: ubuntu-latest
    container: ghcr.io/plc-lang/rust-llvm:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Collect metrics (Git)
      if: github.ref_name == 'master'
      run: |
        cargo benchmark --git

    - name: Collect metrics (Local)
      if: github.ref_name != 'master'
      run: |
        cargo benchmark
